language: node_js
node_js: --lts
cache: npm
before_script:
  - export TZ="Asia/Shanghai"
  - git config user.name "Yuan"
  - git config user.email "yuan@hicoder.cn"
  - sed -i "s~https://github.com/yynps/blog~https://${GITHUB_ACCESS_TOKEN}@github.com/yynps/blog~" _config.yml
script:
  - hexo g
  - hexo d
